bmi088_node:
  ros__parameters:
    bus_type: "spi"

    spi_device: "/dev/spidev1.0"
    acc_cs_gpio: 394
    gyro_cs_gpio: 396
    spi_speed_hz: 5000000

    publish_rate_hz: 200
    frame_id: "imu_link"

    acc_range_g: 6
    gyro_range_dps: 500
    acc_odr_hz: 200
    gyro_odr_hz: 200
    
    enable_self_test: true
