bmi088_node:
  ros__parameters:
    frame_id: "imu_link"
    output_topic: "imu/data_calibrated"

    iio_device_path: "/dev/iio:device1"
    iio_sysfs_dir: "/sys/bus/iio/devices/iio:device1"
    buffer_length: 128
    poll_timeout_ms: 200

    acc_range_g: 6
    gyro_range_dps: 500
    accel_sampling_hz: 400
    gyro_sampling_hz: 400
